version: '2'
services:
    mirror-maker:
      image: wurstmeister/kafka:0.10.0.1
      command: "/scripts/mirror-maker-entrypoint.sh"
      volumes:
        - "./scripts:/scripts:ro"
        - "./config/consumer.properties:/opt/kafka_2.11-0.10.0.1/config/consumer.properties:ro"
        - "./config/producer.properties:/opt/kafka_2.11-0.10.0.1/config/producer.properties:ro"
